---
abstract: 'Parse and edit and TCX activity and course files from GPS training devices'
author:
  - 'Patrick Joly <patjol@cpan.org>'
build_requires:
  Module::Build: '0.28'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  Module::Build: '0.28'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.025, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Geo-TCX
requires:
  DateTime: '0'
  DateTime::Format::ISO8601: '0'
  Geo::Calc: '0'
  Geo::Gpx: '1.02'
  Test::More: '0'
  perl: '5.008'
resources:
  homepage: https://github.com/patjoly/geo-tcx
  repository: https://github.com/patjoly/geo-tcx.git
version: '1.01'
x_generated_by_perl: v5.36.0
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
